namespace :populate_sys_param3 do
	desc "Work Characterstics"
	task :Work_Characterstics => :environment do
		systemParamCategories = SystemParamCategory.create(description:"Work Characterstics",created_by: 1,updated_by: 1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5723" ,value:"E",description:"Vol Disabled Long Term",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5722" ,value:"E",description:"Vol disabled 2nd Parent",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5721" ,value:"E",description:"Victim Domestic Violence",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5720" ,value:"E",description:"Unable part beyond control",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5719" ,value:"E",description:"Treatment severe barriers",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5718" ,value:"I",description:"TEA Work Activity Sanctio",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5717" ,value:"I",description:"TEA Welfare to Work",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5716" ,value:"E",description:"TEA Vol Transp Not Available",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5715" ,value:"I",description:"TEA Vol Supp Svs Not Avai",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5714" ,value:"E",description:"TEA Vol Rehab Refer Disab",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5713" ,value:"E",description:"TEA Vol Pregnant Woman",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5712" ,value:"E",description:"TEA Vol Needed in Home",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5711" ,value:"E",description:"TEA Vol Extra Circumstanc",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5710" ,value:"E",description:"TEA Vol Domestic Violence",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5709" ,value:"E",description:"TEA Vol Chld Care Not Avl",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5708" ,value:"E",description:"TEA Vol Age 60 or older",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5707" ,value:"E",description:"TEA Vol 2 Prnt Care Child",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5706" ,value:"E",description:"TEA Vol 2 Par Disabl Chld",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5705" ,value:"E",description:"TEA Under Age 18 yrs",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5704" ,value:"A",description:"TEA SSA Denial Appeal Pen",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5703" ,value:"I",description:"TEA Rehab-Employment Trac",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5702" ,value:"I",description:"TEA Rehab-Education Track",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5701" ,value:"I",description:"TEA Minor Parent School",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5700" ,value:"I",description:"TEA Minor Parent BU Head",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5699" ,value:"E",description:"TEA LT 2nd Prnt",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5698" ,value:"I",description:"TEA Extnd Unable find job",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5697" ,value:"E",description:"TEA Extnd Rehab Svcs",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5696" ,value:"E",description:"TEA Extnd Par 2 reqd home",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5695" ,value:"E",description:"TEA Extnd No Transportati",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5694" ,value:"E",description:"TEA Extnd No Support Svcs",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5693" ,value:"E",description:"TEA Extnd Extraord Circum",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5692" ,value:"I",description:"TEA Extnd Educ/Training",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5691" ,value:"E",description:"TEA Extnd Domestic Violen",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5690" ,value:"E",description:"TEA Extnd Child Care Unav",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5689" ,value:"E",description:"TEA Extnd Ch<3mo or no CC",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5688" ,value:"I",description:"TEA Extnd Case Circumstan",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5687" ,value:"E",description:"TEA Extnd Cares for Ill",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5686" ,value:"E",description:"TEA Extnd 60 yrs or older",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5685" ,value:"E",description:"TEA Extnd 3rd Trimstr Prg",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5684" ,value:"E",description:"TEA Extnd 2 Par no Fed CC",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5683" ,value:"E",description:"TEA Exempt from Time Limi",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5682" ,value:"E",description:"TEA Defer Transportation",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5681" ,value:"E",description:"TEA Defer Support Serv",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5680" ,value:"E",description:"TEA Defer Rehab Disabilit",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5679" ,value:"E",description:"TEA Defer Extra Circumsta",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5678" ,value:"I",description:"TEA Defer Domestic Viole",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5677" ,value:"E",description:"TEA Defer Child Care",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5676" ,value:"E",description:"TEA Defer Caretaker",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5675" ,value:"E",description:"TEA Defer 3rd Trimester",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5674" ,value:"E",description:"TEA Child is not 3 mo old",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5673" ,value:"A",description:"TEA Child 3-12 mo/no cc",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5672" ,value:"I",description:"TEA 2nd Parent Mandatory",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5671" ,value:"E",description:"TEA 2nd Parent Ill Child",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5670" ,value:"I",description:"TEA 2 Parent Child Care",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5669" ,value:"I",description:"Pending Admin Hearing",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5668" ,value:"A",description:"Participate  ARS workshop",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5667" ,value:"I",description:"Mandatory - TEA",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5666" ,value:"E",description:"Incapacitated Short Term",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5665" ,value:"E",description:"Incapacitated Long Term",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5664" ,value:"E",description:"Extended Fair Hearing",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5663" ,value:"E",description:"Disabled Long-Term TL EXT",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5662" ,value:"E",description:"Disabled Fed TL Ext",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5661" ,value:"E",description:"Disabled 2nd Prnt TL Ext",created_by:1,updated_by:1)
		SystemParam.create(system_param_categories_id:systemParamCategories.id,key:"5660" ,value:"I",description:"60 yrs or older",created_by:1,updated_by:1)
	end
end