namespace :populate_sys_param61 do
	desc "TEA Bonus Closure Reasons"
	task :tea_and_workpays_denials_closure_reasons => :environment do
# TEA closer reasons
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4179",description:"Death",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4180",description:"SSI benefits",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4195",description:"System -SSI Benefits",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4196",description:"Social Security Benefit",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4197",description:"Rail-road Retirement",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4198",description:"Veteran's Benefits",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4199",description:"Change Other Federal",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4200",description:"Change State/Local",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4201",description:"Change Other Pension",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4202",description:"UI-not ESD reported",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4203",description:"UI-ESD reported",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4205",description:"Resources",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4206",description:"TEA 60 months no extension not employed",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4215",description:"Deemed Minor Parent",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4216",description:"Deemed Spouse",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4217",description:"Deemed Parent",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4219",description:"Institutionalized Not LTC",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4221",description:"No Child in Home",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4222",description:"Not State Resident",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4224",description:"Child reached age limit",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4229",description:"Extension Employed Ineligible",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4231",description:"Failed to verify income",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4232",description:"Failed to provide info",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4235",description:"Extended Employment Not extended",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4236",description:"Req Close Extended Employ",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4237",description:"TEA 60 mo no ext employed",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4238",description:"Requested closure",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4239",description:"Unable to locate",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4240",description:"Requested closure-Step-parent",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4246",description:"Child Support Income",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4255",description:"Unable to locate-mail",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4264",description:"Work Activity Non compliance-6mo",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4266",description:"Work Activity Non-compliance Closure",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4286",description:"Drug Conviction",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4296",description:"TEA Extra Payment-Earning",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4297",description:"TEA Close Employed 24 Mo",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4298",description:"TEA Close Extend Found Employment",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4299",description:"TEA Close Ineligible During Ext",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4300",description:"TEA Close Employed at End Extension",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4303",description:"TEA Extra Payments-Request",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4309",description:"Minor Parent Turned 18 yr",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4324",description:"Teen not living with adult",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4325",description:"TEA Class Attendance",created_by: 1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_CLOSE_REASONS",value:"4331",description:"Request Preserve Life Benefits",created_by: 1,updated_by: 1)
# workpays denial reasons
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4006",description:"Not verified-Resident",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4008",description:"Not verified-Child in Home",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4011",description:"Not verified-Income",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4022",description:"Unable to locate",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4025",description:"Death",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4041",description:"Failed to meet participant",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4042",description:"Work Pays Time limit met",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4043",description:"Failed to provide information",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4044",description:"Earnings Exceed FPL",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_DENIAL_REASONS",value:"4045",description:"3 months TEA not received",created_by:1,updated_by: 1)

	#workpays closers reasons
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4224",description:"Child reached age limit",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4284",description:"Citizenship Not Verified",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4336",description:"Earnings Exceeds FPL",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4337",description:"Failed to meet participation",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4338",description:"Work Pays time limit met",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"WORK_PAYS_CLOSE_REASONS",value:"4340",description:"Failed to meet Initial Eligibility",created_by:1,updated_by: 1)

	# TEA Denials
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4006",description:"Not verified-Resident",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4007",description:"Not verified-age",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4008",description:"Not verified-Child in Home",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4009",description:"Not compliance-Work Activity",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4011",description:"Not verified-Income",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4012",description:"Not verified-Resources",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4013",description:"Not verified-Relationship",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4014",description:"Not verified-other",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4015",description:"Not compliant-Interview",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4017",description:"Withdrew-Child Support",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4018",description:"Withdrew-No reason given",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4021",description:"Withdrew-Employed",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4022",description:"Unable to locate",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4023",description:"Moved to Out of  State",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4025",description:"Death",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4026",description:"Already active case",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4033",description:"TEA Lifetime limit",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4043",description:"Failed to provide information",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6410",description:"Income- Excess Earned",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6434",description:"Resources-Other",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6431",description:"Relationship not met",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6423",description:"No Child in home",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6429",description:"Not Resident",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6442",description:"TEA-PRA",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6441",description:"TEA-Diversion Assistance",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6443",description:"Apply/Accept Income",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"4166",description:"TEA-Adult Supervised situation",created_by:1,updated_by: 1)
	SystemParam.create(system_param_categories_id: 9,key:"TEA_DENIAL_REASONS",value:"6426",description:"Not Citizenship/Legal Ali",created_by:1,updated_by: 1)






	end
end