namespace :populate_codetable274 do
	desc "adding Interest Profiler questions"
	task :adding_interest_profiler_questions => :environment do
		code_table = CodeTable.create(name:"Interest Profiler questions",description:"Interest Profiler questions")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Build kitchen cabinets",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Lay brick or tile",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Develop a new medicine",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Study ways to reduce water pollution",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Write books or plays",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Play a musical instrument",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Teach an individual an exercise routine",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Help people with personal or emotional problems",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Buy and sell stocks and bonds",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Manage a retail store",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Develop a spreadsheet using computer software",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Proofread records or forms",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Repair household appliances",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Raise fish in a fish hatchery",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Conduct chemical experiments",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Study the movement of planets",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Compose or arrange music",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Draw pictures",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Give career guidance to people",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Perform rehabilitation therapyEnterprising",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Operate a beauty salon or barber shop",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Manage a department within a large company",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Load computer software into a large computer network",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Operate a calculator",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Assemble electronic parts",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Drive a truck to deliver packages to offices and homes",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Examine blood samples using a microscope",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Investigate the cause of a fire",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Create special effects for movies",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Paint sets for plays",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Do volunteer work at a non-profit organization",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Teach children how to play sports",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Start your own business",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Negotiate business contracts",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Keep shipping and receiving records",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Calculate the wages of employees",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Test the quality of parts before shipment",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Repair and install locks",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Develop a way to better predict the weather",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Work in a biology lab",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Write scripts for movies or television shows",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Perform jazz or tap dance",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Teach sign language to people with hearing disabilities",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Help conduct a group therapy session",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Represent a client in a lawsuit",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Market a new line of clothing",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Inventory supplies using a hand-held computer",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Record rent payments",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Set up and operate machines to make products",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Realistic",long_description:"Put out forest fires",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Invent a replacement for sugar",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Investigative",long_description:"Do laboratory tests to identify diseases",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Sing in a band",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Artistic",long_description:"Edit movies",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Take care of children at a day-care center",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Social",long_description:"Teach a high-school class",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Sell merchandise at a department store",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Enterprising",long_description:"Manage a clothing store",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Keep inventory records",system_defined:"TRUE",active:"TRUE")
		CodetableItem.create(code_table_id: code_table.id,short_description:"Conventional",long_description:"Stamp, sort, and distribute mail for an organization",system_defined:"TRUE",active:"TRUE")
	end
end