namespace :populate_codetable196 do
	desc "notes types"
	task :update_notes_type => :environment do
		CodetableItem.where("id = 6039").update_all(long_description: "Phone")
		CodetableItem.where("id = 6050").update_all(long_description: "Immunization")
		CodetableItem.where("id = 6471").update_all(long_description: "Client")
		CodetableItem.where("id = 6472").update_all(long_description: "Client Race")
		CodetableItem.where("id = 6473").update_all(long_description: "Alien")
		CodetableItem.where("id = 6474").update_all(long_description: "Address")
		CodetableItem.where("id = 6475").update_all(long_description: "Client Relationship")
		CodetableItem.where("id = 6476").update_all(long_description: "Characteristic")
		CodetableItem.where("id = 6477").update_all(long_description: "Characteristic")
		CodetableItem.where("id = 6478").update_all(long_description: "Characteristic")
		CodetableItem.where("id = 6479").update_all(long_description: "Characteristic")
		CodetableItem.where("id = 6480").update_all(long_description: "Characteristic")
		CodetableItem.where("id = 6481").update_all(long_description: "Pregnancy")
		CodetableItem.where("id = 6482").update_all(long_description: "Disability")
		CodetableItem.where("id = 6483").update_all(long_description: "Immunization")
		CodetableItem.where("id = 6484").update_all(long_description: "Income")
		CodetableItem.where("id = 6485").update_all(long_description: "Expense")
		CodetableItem.where("id = 6486").update_all(long_description: "Resource")
		CodetableItem.where("id = 6487").update_all(long_description: "Education")
		CodetableItem.where("id = 6488").update_all(long_description: "Employment")
		CodetableItem.where("id = 6489").update_all(long_description: "Sanction")
		CodetableItem.where("id = 6490").update_all(long_description: "Client Parental Responsibility")
		CodetableItem.where("id = 6503").update_all(long_description: "Income Detail")
		CodetableItem.where("id = 6504").update_all(long_description: "Expense Detail")
		CodetableItem.where("id = 6505").update_all(long_description: "Provider")
		CodetableItem.where("id = 6506").update_all(long_description: "Action Plan")
		CodetableItem.where("id = 6507").update_all(long_description: "Action Plan Detail")
		CodetableItem.where("id = 6511").update_all(long_description: "Resource Detail")
		CodetableItem.where("id = 6521").update_all(long_description: "Provider Service")
		CodetableItem.where("id = 6522").update_all(long_description: "Employers")
		CodetableItem.where("id = 6523").update_all(long_description: "School")
		CodetableItem.where("id = 6527").update_all(long_description: "Other")
		CodetableItem.where("id = 6528").update_all(long_description: "Other")
		CodetableItem.where("id = 6529").update_all(long_description: "Other")
	end
end