namespace :create_application_access_rights_for_codetable_values do
	desc "This is a template to create application access rights for codetable values"
	task :create_application_access_rights_for_codetable_values => :environment do

      #6739- "Arwins"
      #6740 - Provider
        ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 869, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 870, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 871, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 872, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 873, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 874, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 875, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 876, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 877, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 878, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 879, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 880, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 881, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 882, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 883, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 884, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 885, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 886, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 887, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 888, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 889, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 890, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 891, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 892, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 893, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 894, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 895, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 896, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 897, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 898, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 899, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 900, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 901, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 902, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 903, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 904, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 905, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 906, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 907, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 908, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 909, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 910, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 911, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6739, ruby_element_id: 912, access:'Y', created_at: Time.now, updated_at: Time.now)
		ApplicationAccessRight.create(application_id: 6740, ruby_element_id: 913, access:'Y', created_at: Time.now, updated_at: Time.now)
	end
end