namespace :buttons_access_rights_for_compliance_officer do
	desc "Creating access rights for compliance officer"
	task :create_access_rights_compliance_officer => :environment do
		user_role_id = 12
		# connection = ActiveRecord::Base.connection()
		# delete_script = "DELETE FROM access_rights where role_id = " + user_role_id.to_s
		# connection.execute(delete_script)
		# "ActionPlansController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 211,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 212,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 213,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 658,    access:'Y') #"Close"
		# "ActionPlanDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 214,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 215,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 216,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 659,    access:'Y') #Add Action"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 660,    access:'Y') #"Add Service"
		# "ActivityHoursController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 217,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 218,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 219,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 661,    access:'Y') #"Add Week"
		# "AdditionalResourcesAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 220,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 221,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 222,    access:'Y') #"Delete"
		# "AddressesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 223,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 224,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 225,    access:'Y') #"Delete"
		# "AlertsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 226,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 227,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 228,    access:'Y') #"Delete"
		# "AliensController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 229,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 230,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 231,    access:'Y') #"Delete"
		# "ApplicationController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 232,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 233,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 234,    access:'Y') #"Delete"
		# "ApplicationEligibilityResultsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 235,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 236,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 237,    access:'Y') #"Delete"
		# "ApplicationMembersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 238,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 239,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 240,    access:'Y') #"Delete"
		# "ApplicationScreeningsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 241,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 242,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 243,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 712,    access:'Y') #"Add Document"
		# "ApplicationServiceProgramsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 244,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 245,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 246,    access:'Y') #"Delete"
		# "AssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 247,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 248,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 249,    access:'Y') #"Delete"
		# "AssessmentBarriersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 250,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 251,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 252,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 662,    access:'Y') #"Complete Assessment"
		# "AssessmentBarrierRecommendationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 253,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 254,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 255,    access:'Y') #"Delete"
		# "AssessmentQuestionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 256,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 257,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 258,    access:'Y') #"Delete"
		# "AssessmentQuestionMetadataController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 259,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 260,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 261,    access:'Y') #"Delete"
		# "AssessmentQuestionMultiResponsesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 262,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 263,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 264,    access:'Y') #"Delete"
		# "AssessmentSectionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 265,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 266,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 267,    access:'Y') #"Delete"
		# "AssessmentStrengthsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 268,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 269,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 270,    access:'Y') #"Delete"
		# "AssessmentSubSectionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 271,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 272,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 273,    access:'Y') #"Delete"
		# "AssessmentSummariesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 274,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 275,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 276,    access:'Y') #"Delete"
		# "AssistanceUnitMembersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 277,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 278,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 279,    access:'Y') #"Delete"
		# "AttopAncestorController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 280,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 281,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 282,    access:'Y') #"Delete"
		# "BenefitsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 283,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 284,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 285,    access:'Y') #"Delete"
		# "BudgetUnitsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 286,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 287,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 288,    access:'Y') #"Delete"
		# "CareerPathwayPlansController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 289,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 290,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 291,    access:'Y') #"Delete"
		# "ChildCareAndParentingAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 292,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 293,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 294,    access:'Y') #"Delete"
		# "ClientsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 295,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 296,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 297,    access:'Y') #"Delete"
		# "ClientsShareController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 298,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 299,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 300,    access:'Y') #"Delete"
		# "ClientActivitiesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 301,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 302,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 303,    access:'Y') #"Delete"
		# "ClientActivityServicesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 304,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 305,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 306,    access:'Y') #"Delete"
		# "ClientApplicationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 307,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 308,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 309,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 663,    access:'Y') #"Complete Application"
		# "ClientAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 310,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 311,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 312,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 665,    access:'Y') #"Complete"
		# "ClientAssessmentAnswersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 313,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 314,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 315,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 664,    access:'Y') #"Review Assessment"
		# "ClientAssessmentHistoriesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 316,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 317,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 318,    access:'Y') #"Delete"
		# "ClientBarriersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 319,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 320,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 321,    access:'Y') #"Delete"
		# "ClientCharacteristicsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 322,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 323,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 324,    access:'Y') #"Delete"
		# "ClientDocVerficationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 325,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 326,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 327,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 666,    access:'Y') #"FC Add Document"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 667,    access:'Y') #"Upload"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 668,    access:'Y') #"FC Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 669,    access:'Y') #"EC Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 670,    access:'Y') #"FC Upload"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 671,    access:'Y') #"OPUD Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 672,    access:'Y') #"OPUD Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 673,    access:'Y') #"OPUD Upload"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 674,    access:'Y') #"PUD Add Document"
		# "ClientImmunizationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 328,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 329,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 330,    access:'Y') #"Delete"
		# "ClientIncomesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 331,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 332,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 333,    access:'Y') #"Delete"
		# "ClientParentalRspabilitiesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 334,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 335,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 336,    access:'Y') #"Delete"
		# "ClientRacesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 337,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 338,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 339,    access:'Y') #"Delete"
		# "ClientReferralsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 340,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 341,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 342,    access:'Y') #"Delete"
		# "ClientRelationshipsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 343,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 344,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 345,    access:'Y') #"Delete"
		# "ClientResourcesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 346,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 347,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 348,    access:'Y') #"Delete"
		# "ClientScoresController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 349,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 350,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 351,    access:'Y') #"Delete"
		# "ClientSkillsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 352,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 353,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 354,    access:'Y') #"Delete"
		# "CodetableItemsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 355,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 356,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 357,    access:'Y') #"Delete"
		# "CodeTablesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 358,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 359,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 360,    access:'Y') #"Delete"
		# "CostCentersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 361,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 362,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 363,    access:'Y') #"Delete"
		# "DataValidationController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 364,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 365,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 366,    access:'Y') #"Delete"
		# "DisabilitiesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 367,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 368,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 369,    access:'Y') #"Delete"
		# "DomesticViolenceAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 370,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 371,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 372,    access:'Y') #"Delete"
		# "EducationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 373,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 374,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 375,    access:'Y') #"Delete"
		# "EducationAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 376,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 377,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 378,    access:'Y') #"Delete"
		# "EmployersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 379,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 380,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 381,    access:'Y') #"Delete"
		# "EmployerAddressesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 382,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 383,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 384,    access:'Y') #"Delete"
		# "EmployerContactsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 385,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 386,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 387,    access:'Y') #"Delete"
		# "EmploymentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 388,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 389,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 390,    access:'Y') #"Delete"
		# "EmploymentAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 391,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 392,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 393,    access:'Y') #"Delete"
		# "EmploymentDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 394,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 395,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 396,    access:'Y') #"Delete"
		# "EmploymentPlansController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 397,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 398,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 399,    access:'Y') #"Delete"
		# "EmploymentPlanDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 400,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 401,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 402,    access:'Y') #"Delete"
		# "ExpectedWorkParticipationHoursController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 403,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 404,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 405,    access:'Y') #"Delete"
		# "ExpensesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 406,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 407,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 408,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 710,    access:'Y') #"Share"
		# "ExpenseDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 409,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 410,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 411,    access:'Y') #"Delete"
		# "FinalThoughtsAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 412,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 413,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 414,    access:'Y') #"Delete"
		# "GeneralHealthAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 415,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 416,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 417,    access:'Y') #"Delete"
		# "GenericController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 418,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 419,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 420,    access:'Y') #"Delete"
		# "HouseholdsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 421,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 422,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 423,    access:'Y') #"Delete"
		# "HouseholdMembersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 424,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 425,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 426,    access:'Y') #"Delete"
		# "HousingAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 427,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 428,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 429,    access:'Y') #"Delete"
		# "ImmunizationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 430,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 431,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 432,    access:'Y') #"Delete"
		# "IncomesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 433,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 434,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 435,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 675,    access:'Y') #"Share"
		# "IncomeDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 436,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 437,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 438,    access:'Y') #"Delete"
		# "IncomeDetailAdjustReasonsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 439,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 440,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 441,    access:'Y') #"Delete"
		# "InputTypesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 442,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 443,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 444,    access:'Y') #"Delete"
		# "InterviewQuestionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 445,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 446,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 447,    access:'Y') #"Delete"
		# "InStatePaymentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 448,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 449,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 450,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 713,    access:'Y') #"PUISP Edit"
		# "LocalOfficeInformationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 451,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 452,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 453,    access:'Y') #"Delete"
		# "MentalHealthAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 454,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 455,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 456,    access:'Y') #"Delete"
		# "ModalClientSearchController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 457,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 458,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 459,    access:'Y') #"Delete"
		# "NoticeTextsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 460,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 461,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 462,    access:'Y') #"Delete"
		# "OutcomesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 463,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 464,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 465,    access:'Y') #"Delete"
		# "OutOfStatePaymentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 466,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 467,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 468,    access:'Y') #"Delete"
		# "PasswordResetController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 469,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 470,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 471,    access:'Y') #"Delete"
		# "PaymentLineItemsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 472,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 473,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 474,    access:'Y') #"Delete"
		# "PhonesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 475,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 476,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 477,    access:'Y') #"Delete"
		# "PotentialIntakeClientsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 478,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 479,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 480,    access:'Y') #"Delete"
		# "PregnanciesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 481,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 482,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 483,    access:'Y') #"Delete"
		# "PregnancyAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 484,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 485,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 486,    access:'Y') #"Delete"
		# "PrescreenHouseholdsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 487,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 488,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 489,    access:'Y') #"Delete"
		# "ProgramBenefitDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 490,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 491,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 492,    access:'Y') #"Delete"
		# "ProgramBenefitMembersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 493,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 494,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 495,    access:'Y') #"Delete"
		# "ProgramMemberDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 496,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 497,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 498,    access:'Y') #"Delete"
		# "ProgramMemberSummariesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 499,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 500,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 501,    access:'Y') #"Delete"
		# "ProgramMonthSummariesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 502,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 503,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 504,    access:'Y') #"Delete"
		# "ProgramStandardsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 505,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 506,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 507,    access:'Y') #"Delete"
		# "ProgramStandardDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 508,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 509,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 510,    access:'Y') #"Delete"
		# "ProgramUnitsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 511,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 512,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 513,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 676,    access:'Y') #"Start"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 677,    access:'Y') #"Assign Case Manager"
		# "ProgramUnitActionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 514,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 515,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 516,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 714,    access:'Y') #"Action"
		# "ProgramUnitMembersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 517,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 518,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 519,    access:'Y') #"Delete"
		# "ProgramUnitParticipationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 520,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 521,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 522,    access:'Y') #"Delete"
		# "ProgramUnitRepresentativesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 523,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 524,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 525,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 678,    access:'Y') #"Deactivate"
		# "ProgramUnitSizeStandardsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 526,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 527,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 528,    access:'Y') #"Delete"
		# "ProgramUnitSizeStandardDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 529,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 530,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 531,    access:'Y') #"Delete"
		# "ProgramWizardsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 532,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 533,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 534,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 679,    access:'Y') #"Dispose"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 680,    access:'Y') #"Retain"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 681,    access:'Y') #"Eligibility Determination"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 682,    access:'Y') #"Complete Program Unit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 683,    access:'Y') #"Submit Payment"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 684,    access:'Y') #"Mark Active"
		# "ProvidersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 535,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 536,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 537,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 685,    access:'Y') #"Add Branch Office"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 686,    access:'Y') #"Edit Branch Office"
		# "ProviderAddressesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 538,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 539,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 540,    access:'Y') #"Delete"
		# "ProviderAgreementsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 541,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 542,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 543,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 687,    access:'Y') #"Approve"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 688,    access:'Y') #"Terminate"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 689,    access:'Y') #"Print Agreement"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 690,    access:'Y') #"Request For Approval"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 691,    access:'Y') #"Reject"
		# "ProviderContactsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 544,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 545,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 546,    access:'Y') #"Delete"
		# "ProviderInvoicesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 547,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 548,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 549,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 692,    access:'Y') #"Authorize"
		# "ProviderLanguagesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 550,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 551,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 552,    access:'Y') #"Delete"
		# "ProviderServicesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 553,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 554,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 555,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 693,    access:'Y') #"PSAA New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 694,    access:'Y') #"PSAA Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 695,    access:'Y') #"PSAA Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 696,    access:'Y') #"PSA New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 697,    access:'Y') #"PSA Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 698,    access:'Y') #"PSA Delete"
		# "RecommendationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 556,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 557,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 558,    access:'Y') #"Delete"
		# "RelationshipsAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 559,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 560,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 561,    access:'Y') #"Delete"
		# "ResourcesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 562,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 563,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 564,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 699,    access:'Y') #"Share"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 711,    access:'Y') #"Share Delete"
		# "ResourceAdjustmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 565,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 566,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 567,    access:'Y') #"Delete"
		# "ResourceDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 568,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 569,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 570,    access:'Y') #"Delete"
		# "ResourceUsesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 571,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 572,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 573,    access:'Y') #"Delete"
		# "RulesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 574,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 575,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 576,    access:'Y') #"Delete"
		# "RuleAdjustmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 577,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 578,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 579,    access:'Y') #"Delete"
		# "RuleDateParamsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 580,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 581,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 582,    access:'Y') #"Delete"
		# "RuleDateParamDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 583,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 584,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 585,    access:'Y') #"Delete"
		# "RuleDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 586,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 587,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 588,    access:'Y') #"Delete"
		# "RuleDisallowsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 589,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 590,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 591,    access:'Y') #"Delete"
		# "RuleResultsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 592,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 593,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 594,    access:'Y') #"Delete"
		# "SanctionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 595,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 596,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 597,    access:'Y') #"Delete"
		# "SanctionDetailsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 598,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 599,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 600,    access:'Y') #"Delete"
		# "SchedulesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 601,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 602,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 603,    access:'Y') #"Delete"
		# "SchoolsAddressesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 604,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 605,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 606,    access:'Y') #"Delete"
		# "SchoolsContactsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 607,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 608,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 609,    access:'Y') #"Delete"
		# "SchoolsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 610,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 611,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 612,    access:'Y') #"Delete"
		# "ServiceAuthorizationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 613,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 614,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 615,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 700,    access:'Y') #"NTSS Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 701,    access:'Y') #"NTSS Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 702,    access:'Y') #"Approve Service"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 703,    access:'Y') #"SASSS NT Approve"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 704,    access:'Y') #"SASSS T Approve"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 705,    access:'Y') #"Program Management"
		# "ServiceAuthorizationLineItemsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 616,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 617,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 618,    access:'Y') #"Delete"
		# "ServiceProgramsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 619,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 620,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 621,    access:'Y') #"Delete"
		# "StandardRecommendationsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 622,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 623,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 624,    access:'Y') #"Delete"
		# "SubstanceAbuseAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 625,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 626,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 627,    access:'Y') #"Delete"
		# "SuplRetroBnsPaymentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 628,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 629,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 630,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 706,    access:'Y') #"Activate Program Unit"
		# "SystemAlertsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 631,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 632,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 633,    access:'Y') #"Delete"
		# "SystemParamsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 634,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 635,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 636,    access:'Y') #"Delete"
		# "SystemParamCategoriesController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 637,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 638,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 639,    access:'Y') #"Delete"
		# "TimeLimitsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 640,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 641,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 642,    access:'Y') #"Delete"
		# "TransportationAssessmentsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 643,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 644,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 645,    access:'Y') #"Delete"
		# "UsersController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 646,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 647,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 648,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 707,    access:'Y') #"Reset Password"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 708,    access:'Y') #"Change Password"
		# "UserSessionsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 649,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 650,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 651,    access:'Y') #"Delete"
		# "WorkLoadManagementsController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 652,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 653,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 654,    access:'Y') #"Delete"
		# "WorkTasksController"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 655,    access:'Y') #"New"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 656,    access:'Y') #"Edit"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 657,    access:'Y') #"Delete"
		AccessRight.create(role_id: user_role_id, ruby_element_id: 709,    access:'Y') #"Work on the Task"
		# #
		# AccessRight.create(role_id: user_role_id, ruby_element_id: ,    access:'Y') #"New"
		# AccessRight.create(role_id: user_role_id, ruby_element_id: ,    access:'Y') #"Edit"
		# AccessRight.create(role_id: user_role_id, ruby_element_id: ,    access:'Y') #"Delete"

		field_object = RubyElement.create(element_name:"SanctionsController",element_title:"infraction_end_date", element_type: 6368)
		user_role_id = 2 # System Support user
		   AccessRight.create(role_id: user_role_id, ruby_element_id: field_object.id,  access:'Y', created_at: Time.now, updated_at: Time.now)

		user_role_id = 12 # Compliance Officer
			AccessRight.create(role_id: user_role_id, ruby_element_id: field_object.id,  access:'Y', created_at: Time.now, updated_at: Time.now)
	end
end