namespace :add_ruby_elements_for_codetable_values do
	desc "Add ruby elements for codetable values"
	task :add_ruby_elements_for_codetable_values => :environment do
		RubyElement.create(element_name:"6634",element_title:"Change in Case Manager of Program Unit", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6622",element_title:"Approve service payment amount above threshold", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6612",element_title:"First Time Program Unit Reject", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6606",element_title:"Employment Detail", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6604",element_title:"Reject Provider Payment", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6603",element_title:"Reject Provider Agreement", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6530",element_title:"Client Characteristics Information Changed", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6463",element_title:"Request to approve career plan", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6385",element_title:"Provider invoice rejection", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6384",element_title:"Service payment line item rejection", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"5877",element_title:"Duplicate Participation", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2177",element_title:"SERVICE MANAGER-CHAR", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2176",element_title:"Assign different user to program unit", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2175",element_title:"TEA SANCTION", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2174",element_title:"Job Retention -Transfer", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2173",element_title:"Client Information Changed", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2171",element_title:"SSI Termination", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2170",element_title:"SERVICE CASE REFERRAL", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2169",element_title:"SSI New Case Match", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2167",element_title:"Case Error", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2166",element_title:"Notice Rejection", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2165",element_title:"Review Budget Record", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2164",element_title:"Quarterly Wage", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2163",element_title:"Annual Review", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2162",element_title:"On-line Application Review", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2161",element_title:"Child Support Non-Coop", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2160",element_title:"Monthly Unemployment", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2159",element_title:"Medical Review Team", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2157",element_title:"Job Retention - Review", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2156",element_title:"Internal Revenue Match", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2155",element_title:"SNAP-Transfer", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2153",element_title:"SERVICE MANAGER-EMPLOY", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2152",element_title:"Death Match", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2151",element_title:"Deferral/Exemption Follow", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2150",element_title:"Work Pays Case Change", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2149",element_title:"Child Support Exceed Grant", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2148",element_title:"CS Non-Coop-Budget Error", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2147",element_title:"Case Change", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2146",element_title:"Critical Age", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2145",element_title:"Income Mismatch", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2143",element_title:"Service payment line items Approval", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2141",element_title:"Application Follow Up", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2139",element_title:"Case Ineligible Error", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"2138",element_title:"Eligibility Warning Follow up", element_type: 6737, element_microhelp: "ARWINS")
		RubyElement.create(element_name:"6738",element_title:"other", element_type: 6737, element_microhelp: "PROVIDER")
	end
end
