namespace :assessment_questions_multi_response_pregnancy_task55 do

	desc "Assessment Pregnancy"
	task :assessment_questions_multi_response_pregnancy => :environment do

		AssessmentQuestionMultiResponse.create(assessment_question_id:735,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:735,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:736,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:736,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:737,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:737,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:738,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:738,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:738,txt:"Maybe",val:"Maybe",display_order: 3,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:740,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:740,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:741,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:741,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:742,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:744,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:746,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:748,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:748,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:748,txt:"Maybe",val:"Maybe",display_order: 3,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:749,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:756,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:756,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:757,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:757,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:758,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:758,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:759,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:759,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:751,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:761,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:761,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:762,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:762,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:763,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:763,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:764,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:764,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"",val:"",display_order: 0,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Birth/Adoptive Child",val:"Birth/AdoptiveChild",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Grand/Great Child",val:"Grand/GreatChild",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Stepchild",val:"Stepchild",display_order: 3,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Other/Unrel Child",val:"Other/UnrelChild",display_order: 4,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Spousal Parent",val:"SpousalParent",display_order: 5,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Non-Parental Spouse",val:"Non-ParentalSpouse",display_order: 6,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Other Parent",val:"OtherParent",display_order: 7,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Niece/Nephew",val:"Niece/Nephew",display_order: 8,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"First Cousin",val:"FirstCousin",display_order: 9,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Aunt/Uncle",val:"Aunt/Uncle",display_order: 10,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Sibling",val:"Sibling",display_order: 11,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Step-sibling",val:"Step-sibling",display_order: 12,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Other Rel. Adult",val:"OtherRel.Adult",display_order: 13,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Other Unral. Adult",val:"OtherUnral.Adult",display_order: 14,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Child w/child",val:"Childw/child",display_order: 15,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Child Parent",val:"ChildParent",display_order: 16,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:753,txt:"Live-in Boyfriend/Girlfriend",val:"Live-inBoyfriend/Girlfriend",display_order: 17,created_by: 1,updated_by: 1)

		AssessmentQuestionMultiResponse.create(assessment_question_id:785,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:785,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:786,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:786,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:787,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:787,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:788,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
		AssessmentQuestionMultiResponse.create(assessment_question_id:788,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)


    end
end