namespace :assessment_questions_mtdt_child_care_childcare_status_task69 do
        desc "Assessment Child Care Childcare Status"
        task :assessment_questions_mtdt_child_care_childcare_status => :environment do
                AssessmentQuestionMetadatum.create(assessment_question_id:453,response_data_type:"LABEL",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:454,response_data_type:"LABEL",prompt_style_class: "fi-alert",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:242,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:243,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:687,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:244,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:245,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:246,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:247,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:387,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:388,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:688,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:389,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:390,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:391,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:392,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:393,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:394,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:689,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:395,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:396,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:397,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:398,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:399,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:400,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:690,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:401,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:402,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:403,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:404,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:405,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:406,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:691,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:407,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:408,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:409,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:410,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:411,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:412,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:692,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:413,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:414,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:415,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:416,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:417,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:418,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:693,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:419,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:420,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:421,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:422,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:423,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:424,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:694,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:425,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:426,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:427,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:428,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:429,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:430,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:695,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:431,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:432,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:433,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:434,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:435,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:436,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:696,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:437,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:438,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:439,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:440,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:441,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:442,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:697,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:443,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:444,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:445,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:446,response_data_type:"RADIO",created_by: 1,updated_by: 1)

                AssessmentQuestionMetadatum.create(assessment_question_id:447,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:448,response_data_type:"TEXT",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:698,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:449,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:450,response_data_type:"TEXTAREA",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:451,response_data_type:"RADIO",created_by: 1,updated_by: 1)
                AssessmentQuestionMetadatum.create(assessment_question_id:452,response_data_type:"RADIO",created_by: 1,updated_by: 1)

        end
end