namespace :update_assessment_questions_for_childcare_and_parenting do
	desc "updating Assessment Questions for substance abuse"
	task :update_assessment_questions_for_childcare_and_parenting => :environment do

         # updating sub_section_type from Child issues to childcare status
		AssessmentQuestion.find(724).update(title: "1. Do you have children that are of the age to require child care?",question_text: " 1. Do you have children that are of the age to require child care?",assessment_sub_section_id: 25, display_order: 2)
        AssessmentQuestion.find(725).update(title: " 1a. If so, do you have child care?",question_text: " 1a. If so, do you have child care?" , assessment_sub_section_id: 25, display_order: 3)
        AssessmentQuestion.find(726).update(title: " 1b. Do your child care arrangements provide you the ability to work effectively?", question_text: " 1b. Do your child care arrangements provide you the ability to work effectively?" ,assessment_sub_section_id: 25, display_order: 4)
        #updating display order in childcare status
        AssessmentQuestion.find(454).update( display_order:5)
		AssessmentQuestion.find(242).update( display_order:6)
		AssessmentQuestion.find(243).update( display_order:7)
		AssessmentQuestion.find(687).update( display_order:8)
		AssessmentQuestion.find(244).update( display_order:9)
		AssessmentQuestion.find(245).update( display_order:10)
		AssessmentQuestion.find(246).update( display_order:11)
		AssessmentQuestion.find(247).update( display_order:12)
		AssessmentQuestion.find(387).update( display_order:13)
		AssessmentQuestion.find(388).update( display_order:14)
		AssessmentQuestion.find(688).update( display_order:15)
		AssessmentQuestion.find(389).update( display_order:16)
		AssessmentQuestion.find(390).update( display_order:17)
		AssessmentQuestion.find(391).update( display_order:18)
		AssessmentQuestion.find(392).update( display_order:19)
		AssessmentQuestion.find(393).update( display_order:20)
		AssessmentQuestion.find(394).update( display_order:21)
		AssessmentQuestion.find(689).update( display_order:22)
		AssessmentQuestion.find(395).update( display_order:23)
		AssessmentQuestion.find(396).update( display_order:24)
		AssessmentQuestion.find(397).update( display_order:25)
		AssessmentQuestion.find(398).update( display_order:26)
		AssessmentQuestion.find(399).update( display_order:27)
		AssessmentQuestion.find(400).update( display_order:28)
		AssessmentQuestion.find(690).update( display_order:29)
		AssessmentQuestion.find(401).update( display_order:30)
		AssessmentQuestion.find(402).update( display_order:31)
		AssessmentQuestion.find(403).update( display_order:32)
		AssessmentQuestion.find(404).update( display_order:33)
		AssessmentQuestion.find(405).update( display_order:34)
		AssessmentQuestion.find(406).update( display_order:35)
		AssessmentQuestion.find(691).update( display_order:36)
		AssessmentQuestion.find(407).update( display_order:37)
		AssessmentQuestion.find(408).update( display_order:38)
		AssessmentQuestion.find(409).update( display_order:39)
		AssessmentQuestion.find(410).update( display_order:40)
		AssessmentQuestion.find(411).update( display_order:41)
		AssessmentQuestion.find(412).update( display_order:42)
		AssessmentQuestion.find(692).update( display_order:43)
		AssessmentQuestion.find(413).update( display_order:44)
		AssessmentQuestion.find(414).update( display_order:45)
		AssessmentQuestion.find(415).update( display_order:46)
		AssessmentQuestion.find(416).update( display_order:47)
		AssessmentQuestion.find(417).update( display_order:48)
		AssessmentQuestion.find(418).update( display_order:49)
		AssessmentQuestion.find(693).update( display_order:50)
		AssessmentQuestion.find(419).update( display_order:51)
		AssessmentQuestion.find(420).update( display_order:52)
		AssessmentQuestion.find(421).update( display_order:53)
		AssessmentQuestion.find(422).update( display_order:54)
		AssessmentQuestion.find(423).update( display_order:55)
		AssessmentQuestion.find(424).update( display_order:56)
		AssessmentQuestion.find(694).update( display_order:57)
		AssessmentQuestion.find(425).update( display_order:58)
		AssessmentQuestion.find(426).update( display_order:59)
		AssessmentQuestion.find(427).update( display_order:60)
		AssessmentQuestion.find(428).update( display_order:61)
		AssessmentQuestion.find(429).update( display_order:62)
		AssessmentQuestion.find(430).update( display_order:63)
		AssessmentQuestion.find(695).update( display_order:64)
		AssessmentQuestion.find(431).update( display_order:65)
		AssessmentQuestion.find(432).update( display_order:66)
		AssessmentQuestion.find(433).update( display_order:67)
		AssessmentQuestion.find(434).update( display_order:68)
		AssessmentQuestion.find(435).update( display_order:69)
		AssessmentQuestion.find(436).update( display_order:70)
		AssessmentQuestion.find(696).update( display_order:71)
		AssessmentQuestion.find(437).update( display_order:72)
		AssessmentQuestion.find(438).update( display_order:73)
		AssessmentQuestion.find(439).update( display_order:74)
		AssessmentQuestion.find(440).update( display_order:75)
		AssessmentQuestion.find(441).update( display_order:76)
		AssessmentQuestion.find(442).update( display_order:77)
		AssessmentQuestion.find(697).update( display_order:78)
		AssessmentQuestion.find(443).update( display_order:79)
		AssessmentQuestion.find(444).update( display_order:80)
		AssessmentQuestion.find(445).update( display_order:81)
		AssessmentQuestion.find(446).update( display_order:82)
		AssessmentQuestion.find(447).update( display_order:83)
		AssessmentQuestion.find(448).update( display_order:84)
		AssessmentQuestion.find(698).update( display_order:85)
		AssessmentQuestion.find(449).update( display_order:86)
		AssessmentQuestion.find(450).update( display_order:87)
		AssessmentQuestion.find(451).update( display_order:88)
		AssessmentQuestion.find(452).update( display_order:89)

        #asking a new question in  Parenting and child support
		assessment_question = AssessmentQuestion.create(assessment_sub_section_id:23,title:"Do you have any children with non-custodial parent? Or are you a non-custodial parent of any children?",question_text:"Do you have any children with non-custodial parent? Or are you a non-custodial parent of any children? ",display_order:1,enabled:1,required:1,created_by: 1,updated_by: 1)
		AssessmentQuestionMetadatum.create(assessment_question_id:assessment_question.id,response_data_type:"RADIO",created_by: 1,updated_by: 1)
        AssessmentQuestionMultiResponse.create(assessment_question_id:assessment_question.id,txt:"Yes",val:"Y",display_order: 1,created_by: 1,updated_by: 1)
        AssessmentQuestionMultiResponse.create(assessment_question_id:assessment_question.id,txt:"No",val:"N",display_order: 2,created_by: 1,updated_by: 1)

          # updating display order for Parenting and child support
        AssessmentQuestion.find(563	).update( display_order:2)
		AssessmentQuestion.find(564	).update( display_order:3)
		AssessmentQuestion.find(565	).update( display_order:4)
		AssessmentQuestion.find(727	).update( display_order:5)
		AssessmentQuestion.find(728	).update( display_order:6)
		AssessmentQuestion.find(729	).update( display_order:7)
		AssessmentQuestion.find(730	).update( display_order:8)
		AssessmentQuestion.find(566	).update( display_order:9)
		AssessmentQuestion.find(567	).update( display_order:10)
		AssessmentQuestion.find(765	).update( display_order:11)
		AssessmentQuestion.find(766	).update( display_order:12)
		AssessmentQuestion.find(767	).update( display_order:13)
		AssessmentQuestion.find(568	).update( display_order:14)
		AssessmentQuestion.find(570	).update( display_order:15)
		AssessmentQuestion.find(569	).update( display_order:16)
		AssessmentQuestion.find(571	).update( display_order:17)





  end
end
