namespace :reset_all_id_after_conversion do
	desc "Reset all id's after conversion"
	task :reset_all_id_after_conversion => :environment do

	connection = ActiveRecord::Base.connection()
   	connection.execute("SELECT setval('public.users_id_seq', (select max(id) + 1 from public.users), true)")
	connection.execute("SELECT setval('public.assignments_id_seq', (select max(id) + 1 from public.assignments), true)")
	connection.execute("SELECT setval('public.roles_id_seq', (select max(id) + 1 from public.roles), true)")
	connection.execute("SELECT setval('public.client_relationships_id_seq', (select max(id) + 1 from public.client_relationships), true)")
	connection.execute("SELECT setval('public.access_rights_id_seq', (select max(id) + 1 from public.access_rights), true)")
	connection.execute("SELECT setval('public.ruby_elements_id_seq', (select max(id) + 1 from public.ruby_elements), true)")
	connection.execute("SELECT setval('public.ruby_element_reltns_id_seq', (select max(id) + 1 from public.ruby_element_reltns), true)")
	connection.execute("SELECT setval('public.code_tables_id_seq', (select max(id) + 1 from public.code_tables), true)")
	connection.execute("SELECT setval('public.codetable_items_id_seq', (select max(id) + 1 from public.codetable_items), true)")
	connection.execute("SELECT setval('public.client_incomes_id_seq', (select max(id) + 1 from public.client_incomes), true)")
	connection.execute("SELECT setval('public.income_detail_adjust_reasons_id_seq', (select max(id) + 1 from public.income_detail_adjust_reasons), true)")
	connection.execute("SELECT setval('public.client_races_id_seq', (select max(id) + 1 from public.client_races), true)")
	#connection.execute("SELECT setval('public.client_addresses_id_seq', (select max(id) + 1 from public.client_addresses), true)")
	connection.execute("SELECT setval('public.phones_id_seq', (select max(id) + 1 from public.phones), true)")
	connection.execute("SELECT setval('public.aliens_id_seq', (select max(id) + 1 from public.aliens), true)")
	connection.execute("SELECT setval('public.expenses_id_seq', (select max(id) + 1 from public.expenses), true)")
	connection.execute("SELECT setval('public.client_expenses_id_seq', (select max(id) + 1 from public.client_expenses), true)")
	connection.execute("SELECT setval('public.expense_details_id_seq', (select max(id) + 1 from public.expense_details), true)")
	connection.execute("SELECT setval('public.incomes_id_seq', (select max(id) + 1 from public.incomes), true)")
	connection.execute("SELECT setval('public.income_details_id_seq', (select max(id) + 1 from public.income_details), true)")
	connection.execute("SELECT setval('public.addresses_id_seq', (select max(id) + 1 from public.addresses), true)")
	connection.execute("SELECT setval('public.employments_id_seq', (select max(id) + 1 from public.employments), true)")
	connection.execute("SELECT setval('public.employment_details_id_seq', (select max(id) + 1 from public.employment_details), true)")
	connection.execute("SELECT setval('public.resources_id_seq', (select max(id) + 1 from public.resources), true)")
	connection.execute("SELECT setval('public.resource_details_id_seq', (select max(id) + 1 from public.resource_details), true)")
	connection.execute("SELECT setval('public.resource_adjustments_id_seq', (select max(id) + 1 from public.resource_adjustments), true)")
	connection.execute("SELECT setval('public.resource_uses_id_seq', (select max(id) + 1 from public.resource_uses), true)")
	connection.execute("SELECT setval('public.clients_id_seq', (select max(id) + 1 from public.clients), true)")
	connection.execute("SELECT setval('public.client_resources_id_seq', (select max(id) + 1 from public.client_resources), true)")
	connection.execute("SELECT setval('public.client_parental_rspabilities_id_seq', (select max(id) + 1 from public.client_parental_rspabilities), true)")
	connection.execute("SELECT setval('public.client_referrals_id_seq', (select max(id) + 1 from public.client_referrals), true)")
	connection.execute("SELECT setval('public.client_barriers_id_seq', (select max(id) + 1 from public.client_barriers), true)")
	connection.execute("SELECT setval('public.client_skills_id_seq', (select max(id) + 1 from public.client_skills), true)")
	connection.execute("SELECT setval('public.client_scores_id_seq', (select max(id) + 1 from public.client_scores), true)")
	connection.execute("SELECT setval('public.providers_id_seq', (select max(id) + 1 from public.providers), true)")
	# connection.execute("SELECT setval('public.client_sanctions_id_seq', (select max(id) + 1 from public.client_sanctions), true)")
	# connection.execute("SELECT setval('public.budget_units_id_seq', (select max(id) + 1 from public.budget_units), true)")
	connection.execute("SELECT setval('public.benefits_id_seq', (select max(id) + 1 from public.benefits), true)")
	connection.execute("SELECT setval('public.households_id_seq', (select max(id) + 1 from public.households), true)")
	connection.execute("SELECT setval('public.household_members_id_seq', (select max(id) + 1 from public.household_members), true)")
	connection.execute("SELECT setval('public.pregnancies_id_seq', (select max(id) + 1 from public.pregnancies), true)")
	connection.execute("SELECT setval('public.disabilities_id_seq', (select max(id) + 1 from public.disabilities), true)")
	connection.execute("SELECT setval('public.time_limits_id_seq', (select max(id) + 1 from public.time_limits), true)")
	connection.execute("SELECT setval('public.program_standards_id_seq', (select max(id) + 1 from public.program_standards), true)")
	connection.execute("SELECT setval('public.program_standard_details_id_seq', (select max(id) + 1 from public.program_standard_details), true)")
	connection.execute("SELECT setval('public.service_programs_id_seq', (select max(id) + 1 from public.service_programs), true)")
	connection.execute("SELECT setval('public.system_params_id_seq', (select max(id) + 1 from public.system_params), true)")
	connection.execute("SELECT setval('public.system_param_categories_id_seq', (select max(id) + 1 from public.system_param_categories), true)")
	connection.execute("SELECT setval('public.immunizations_id_seq', (select max(id) + 1 from public.immunizations), true)")
	connection.execute("SELECT setval('public.sanctions_id_seq', (select max(id) + 1 from public.sanctions), true)")
	connection.execute("SELECT setval('public.sanction_details_id_seq', (select max(id) + 1 from public.sanction_details), true)")
	connection.execute("SELECT setval('public.educations_id_seq', (select max(id) + 1 from public.educations), true)")
	connection.execute("SELECT setval('public.client_characteristics_id_seq', (select max(id) + 1 from public.client_characteristics), true)")

	connection.execute("SELECT setval('public.client_applications_id_seq', (select max(id) + 1 from public.client_applications), true)")
	connection.execute("SELECT setval('public.application_members_id_seq', (select max(id) + 1 from public.application_members), true)")
	connection.execute("SELECT setval('public.application_service_programs_id_seq', (select max(id) + 1 from public.application_service_programs), true)")
	connection.execute("SELECT setval('public.program_units_id_seq', (select max(id) + 1 from public.program_units), true)")
	connection.execute("SELECT setval('public.program_unit_members_id_seq', (select max(id) + 1 from public.program_unit_members), true)")
	connection.execute("SELECT setval('public.program_wizards_id_seq', (select max(id) + 1 from public.program_wizards), true)")
	connection.execute("SELECT setval('public.program_benefit_members_id_seq', (select max(id) + 1 from public.program_benefit_members), true)")
	connection.execute("SELECT setval('public.program_month_summaries_id_seq', (select max(id) + 1 from public.program_month_summaries), true)")
	connection.execute("SELECT setval('public.program_benefit_details_id_seq', (select max(id) + 1 from public.program_benefit_details), true)")
	connection.execute("SELECT setval('public.program_member_summaries_id_seq', (select max(id) + 1 from public.program_member_summaries), true)")
	connection.execute("SELECT setval('public.program_member_details_id_seq', (select max(id) + 1 from public.program_member_details), true)")
	connection.execute("SELECT setval('public.program_unit_participations_id_seq', (select max(id) + 1 from public.program_unit_participations), true)")
	connection.execute("SELECT setval('public.client_immunizations_id_seq', (select max(id) + 1 from public.client_immunizations), true)")
	connection.execute("SELECT setval('public.program_wizard_run_id_seq', (select max(run_id) + 1 from public.program_wizards), true)")
	connection.execute("SELECT setval('public.in_state_payments_id_seq', (select max(id) + 1 from public.in_state_payments), true)")
	connection.execute("SELECT setval('public.out_of_state_payments_id_seq', (select max(id) + 1 from public.out_of_state_payments), true)")
	connection.execute("SELECT setval('public.program_unit_representatives_id_seq', (select max(id) + 1 from public.program_unit_representatives), true)")


	# connection.execute("SELECT setval('public.client_characteristics_id_seq', (select max(id) + 1 from public.client_characteristics), true)")

	connection.execute("SELECT setval('public.entity_phones_id_seq', (select max(id) + 1 from public.entity_phones), true)")
	connection.execute("SELECT setval('public.entity_addresses_id_seq', (select max(id) + 1 from public.entity_addresses), true)")

	end

end